### PR TITLE
2019 Updates

### PR DESCRIPTION
**Pull request by dlinch**
Figured this package needed a little love. Hit it with my linter and added some flare of my own.

### CODE REVIEW

**Comment by dlinch** [comment]
@skuttleman ping!

**Comment by skuttleman** [comment]
@dlinch Please tell me you're updating this to use it in production somewhere!

**Comment by dlinch** [comment]
I just wanted to make sure the best dependency in the world wasn't getting stale...

**Comment by skuttleman** [comment]
@dlinch published a new version for you: https://www.npmjs.com/package/debunk

**Pull request merged**
